name: Render Documentation

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/render-documentation.ya?ml"
      - "./libraries/WiFiS3/examples/**"
      - "./libraries/WiFiS3/src/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/render-documentation.ya?ml"
      - "./libraries/WiFiS3/examples/**"
      - "./libraries/WiFiS3/src/**"
  workflow_dispatch:
      
jobs:
  render-docs:
    permissions:
      contents: write
    uses: arduino/render-docs-github-action/.github/workflows/render-docs.yml@main
    with:
      source-path: './libraries/WiFiS3/src'
      target-path: './libraries/WiFiS3/docs/api.md'
      exclude-pattern: 'StringHelpers.h WiFi.h Modem.h'
      commit: ${{ github.event_name != 'pull_request' }} # Only commit changes if not a PR